Fix fetch_binaries_for_coredumps
Addresses error message:

  AttributeError: 'tuple' object has no attribute 'split'

Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>
(cherry picked from commit 807d8b76ca4944f6ad4d36e4ee82922bf3911da9)