tests: use dict() instead Mock() to test config
Addresses failure in verify_package_version:
    TypeError: argument of type 'Mock' is not iterable

Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@gmail.com>
(cherry picked from commit 8a8bd9bd82248c7946f1ab3ab7aaa9cb41f468fc)